services:
  db:
    image: postgres:16
    container_name: studienplaner-db
    environment:
      POSTGRES_DB: studienplaner
      POSTGRES_USER: student
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - studienplaner-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: studienplaner-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - studienplaner-net

  app:
    build: .
    container_name: studienplaner-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/studienplaner
      SPRING_DATASOURCE_USERNAME: student
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - studienplaner-net

volumes:
  pgdata:

networks:
  studienplaner-net:
    driver: bridge
