name: Java CI

on:
  push:
    branches: [ master, dev, msi-installer ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean compile

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: studienplaner-jar
          path: target/Studienplaner-0.0.1-SNAPSHOT.jar

  test-and-coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests and generate coverage
        run: mvn test jacoco:report

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/site/jacoco/jacoco.xml
          fail_ci_if_error: true

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Checkstyle
        run: mvn checkstyle:check

  build-msi:
    if: github.ref == 'refs/heads/msi-installer'
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Build MSI Installer
        run: .\createMsi.bat
        shell: cmd

      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: studienplaner-msi
          path: "*.msi"

  release-msi:
    needs: build-msi
    if: github.ref == 'refs/heads/msi-installer'
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download MSI artifact
        uses: actions/download-artifact@v4
        with:
          name: studienplaner-msi
          path: .

      - name: Get latest release from master
        id: get_latest_release
        uses: actions/github-script@v6
        with:
          script: |
            const releases = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            if (releases.data.length === 0) {
              core.setFailed('No releases found in this repository.');
            }
            // Предполагаем, что релизы отсортированы по дате (первый – последний релиз)
            return releases.data[0].tag_name;
          result-encoding: string

      - name: Update latest release with MSI artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_latest_release.outputs.result }}
          update_release: true
          files: "*.msi"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}


  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: studienplaner-jar
          path: .

      - name: Rename JAR file
        run: mv Studienplaner-0.0.1-SNAPSHOT.jar Studienplaner-${{ github.run_number }}.jar

      - name: Generate changelog
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: ${{ steps.changelog.outputs.changelog }}
          files: Studienplaner-${{ github.run_number }}.jar
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
